== Arquillian Universe unified dependencies

The Arquillian Universe BOM is a 'Bill of Material' Maven POM file collection
that make up a module stack that stretch across the whole Arquillian Universe.

This project aim to fulfill two main requirements:

. Simplify the 'Getting Started' experience
. Unify naming and versions

=== Usage

Include the following snippet in your POM xml file:

[source, xml]
----
<properties>
    <version.arquillian_universe>1.0.0.Alpha1</version.arquillian_universe>
</properties>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.arquillian</groupId>
            <artifactId>arquillian-universe</artifactId>
            <version>${version.arquillian_universe}</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>
----

Then include the individual modules as you see fit, by simply depending on the unified pom name:

[source, xml]
----
<dependencies>
    <dependency>
        <groupId>org.arquillian.universe</groupId>
        <artifactId>arquillian-junit</artifactId>
        <scope>test</scope>
        <type>pom</type>
    </dependency>
</dependencies>
----

=== Available modules

==== JUnit

The JUnit Container integration.

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-junit</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

===== Additional required dependencies

[source, xml]
----
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>${version.junit}</version>
    <scope>test</scope>
</dependency>
----

==== JUnit Standalone

The JUnit Standalone integration.

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-junit-standalone</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

===== Additional required dependencies

[source, xml]
----
<dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>${version.junit}</version>
    <scope>test</scope>
</dependency>
----

==== TestNG

The TestNG Container integration.

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-testng</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

===== Additional required dependencies

[source, xml]
----
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>${version.testng}</version>
    <scope>test</scope>
</dependency>
----

==== TestNG Standalone

The TestNG Standalone integration.

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-testng-standalone</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

===== Additional required dependencies

[source, xml]
----
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>${version.testng}</version>
    <scope>test</scope>
</dependency>
----

==== Cuckes in Space

Cukes in Space! allows you to deploy and run Cucumber features in the application server of your choice using the Arquillian test framework.

Documentation: https://github.com/cukespace/cukespace

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-cuckes</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

===== Optional Dependencies

[source, xml]
----
<dependency>
    <groupId>info.cukes</groupId>
    <artifactId>cucumber-java8</artifactId>
</dependency>
----

==== Arquillian Drone

The Arquillian Drone provides a simple way how to write functional tests for an application with a web-based user interface. Arquillian Drone brings the power of WebDriver into the Arquillian framework. WebDriver provides a language how to communicate with a browser, like filling the forms, navigating on the pages and validating their content.

Documentation: https://github.com/arquillian/arquillian-extension-drone

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-drone</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

==== Arquillian Graphene

Graphene project is designed as set of extensions for Selenium WebDriver project focused on rapid development and usability in Java environment.

Documentation: https://github.com/arquillian/arquillian-graphene

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-graphene</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

NOTE: you don't need to add `arquillian-drone` dependency since it is automatically added when using `arquillian-graphene`.

==== Arquillian Graphene Recorder

Browser screenshooter is an extension to Arquillian platform which provides the possibility to take screenshots of your tests. Only browser window is screened.

Documentation: https://github.com/arquillian/arquillian-graphene/tree/master/extension/screenshooter

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-graphene-recorder</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

NOTE: you don't need to add `arquillian-graphene` or `arquillian-recorder` dependency since it is automatically added when using `arquillian-graphene-recorder`.

==== Arquillian Warp

Warp fills the void between client-side and server-side testing.

This extension allow you to write client-side test which asserts server-side logic.

Documentation: https://github.com/arquillian/arquillian-extension-warp

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-warp</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

==== Arquillian Warp JSF

Warp JSF adds additional Warp capabilities to JSF requests.

Documentation: https://github.com/arquillian/arquillian-extension-warp

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-warp-jsf</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

NOTE: you don't need to add `arquillian-warp` dependency since it is automatically added when using `arquillian-warp-jsf`.

==== Arquillian Transaction JTA

Arquillian Transaction Extension allow you to influence the Transactional behavior of the Test via annotations.

Documentation: https://github.com/arquillian/arquillian-extension-transaction

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-transaction-jta</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

==== Arquillian Persistence

Arquillian Persistence Extension was created to help you writing tests where persistence layer is involved. Inspired by great framework called Unitils, it brings bunch of annotations to help you deal with the underlying data storage.

Documentation: https://github.com/arquillian/arquillian-extension-persistence

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-persistence</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

NOTE: you don't need to add `arquillian-transaction-jta` dependency since it is automatically added when using `arquillian-persistence`.

==== Arquillian Spring

Documentation: https://github.com/arquillian/arquillian-extension-spring

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-spring</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

===== Additional required dependencies

The Spring framework core and modules of choice.

==== Arquillian Spring Transaction

Documentation: https://github.com/arquillian/arquillian-extension-spring

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-spring-transaction</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

NOTE: you don't need to add `arquillian-spring` or `arquillian-transaction` dependency since it is automatically added when using `arquillian-spring-transaction`.

===== Additional required dependencies

The Spring framework core and modules of choice.

==== Arquillian Spring Persistence

Documentation: https://github.com/arquillian/arquillian-extension-spring

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-spring-persistence</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

NOTE: you don't need to add `arquillian-spring` or `arquillian-persistence` dependency since it is automatically added when using `arquillian-spring-persistence`.

===== Additional required dependencies

The Spring framework core and modules of choice.

==== Arquillian Spring Warp

Documentation: https://github.com/arquillian/arquillian-extension-spring

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-spring-warp</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

NOTE: you don't need to add `arquillian-spring` or `arquillian-warp` dependency since it is automatically added when using `arquillian-spring-warp`.

===== Additional required dependencies

The Spring framework core and modules of choice.

==== Arquillian Byteman

Byteman integration for the Arquillian Project

Mocking 2.0, Runtime bytecode manipulation in Integration tests.

Documentation: https://github.com/arquillian/arquillian-extension-byteman

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-byteman</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

===== Additional required dependencies

[source, xml]
----
<dependency>
    <groupId>org.jboss.byteman</groupId>
    <artifactId>byteman-submit</artifactId>
    <version>${version.byteman}</version>
    <scope>test</scope>
</dependency>
----

==== Arquillian Jacoco

Automagic remote in-container code coverage

Documentation: https://github.com/arquillian/arquillian-extension-jacoco

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-jacoco</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

===== Additional required dependencies

[source, xml]
----
<dependency>
    <groupId>org.jacoco</groupId>
    <artifactId>org.jacoco.core</artifactId>
    <version>${version.jacoco}</version>
    <scope>test</scope>
</dependency>
----

NOTE: See documentation for additional Maven configuration.

==== Arquillian Recorder

Arquillian Recorder project brings neat reports of your Arquillian tests.

Documentation: https://github.com/arquillian/arquillian-recorder/wiki/Reporter  + 
Documentation: https://github.com/arquillian/arquillian-recorder/wiki/Screenshooter + 
Documentation: https://github.com/arquillian/arquillian-recorder/wiki + 

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-recorder</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

==== Arquillian Cube Docker

Arquillian Cube is an Arquillian extension that can be used to manager Docker containers from Arquillian.

With this extension you can start a Docker container with a server installed, deploy the required deployable file within it and execute Arquillian tests.

The key point here is that if Docker is used as deployable platform in production, your tests are executed in a the same container as it will be in production, so your tests are even more real than before.

But it also lets you start a container with every required service like database, mail server, …​ and instead of stubbing or using fake objects your tests can use real servers.

Documentation: https://github.com/arquillian/arquillian-cube

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-cube-docker</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

==== Arquillian Cube OpenShift

Arquillian Cube is an Arquillian extension that can be used to manager Docker containers from Arquillian.

Documentation: https://github.com/arquillian/arquillian-cube

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-cube-openshift</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

==== Arquillian Cube Containerless

Arquillian Cube is an Arquillian extension that can be used to manager Docker containers from Arquillian.

The Containerless container integrates Docker images as normal Arquillian Containers without the need for any Java EE style server as a target.

Documentation: https://github.com/arquillian/arquillian-cube#containerless-server-and-docker

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-cube-containerless</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----

==== Arquillian Chameleon Container

Have you ever faced an issue that switching between container implementations isn’t that easy?

Testing against several containers (JBoss AS / JBoss EAP / WildFly) or even switching between different modes (Managed, Remote, Embedded) may result in bloated pom.xml.

Chameleon Containers are able to quickly adopt to your needs without too much hassle.

Documentation: https://github.com/arquillian/arquillian-container-chameleon

[source, xml]
----
<dependency>
    <groupId>org.arquillian.universe</groupId>
    <artifactId>arquillian-chameleon</artifactId>
    <scope>test</scope>
    <type>pom</type>
</dependency>
----
